#!/bin/bash
#wux 2014-10-03
#hopefully turn off shit for movies etc..

#check for XLOCK:
if [ `pgrep xautolock` ]; then
    killall xautolock
    fi

xset s noblank
xset s off
xset -dpms
xset -b

echo -e "Movie Mode. \nEnjoy"
